version: '3.9'

services:
  postgres:
    image: postgres
    container_name: app-database
    ports:
      - "4444:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      
  app:
    build: .
    depends_on:
      - postgres
    restart: always
    ports:
      - 6666:8080
