"""initial

Revision ID: aaa5f61961e2
Revises: 
Create Date: 2023-08-15 21:37:17.101511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaa5f61961e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hash_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('problem_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('update_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hash_records_hash'), 'hash_records', ['hash'], unique=False)
    op.create_index(op.f('ix_hash_records_id'), 'hash_records', ['id'], unique=False)
    op.create_index(op.f('ix_hash_records_problem_id'), 'hash_records', ['problem_id'], unique=False)
    op.create_table('problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('body', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('update_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problems_id'), 'problems', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problems_id'), table_name='problems')
    op.drop_table('problems')
    op.drop_index(op.f('ix_hash_records_problem_id'), table_name='hash_records')
    op.drop_index(op.f('ix_hash_records_id'), table_name='hash_records')
    op.drop_index(op.f('ix_hash_records_hash'), table_name='hash_records')
    op.drop_table('hash_records')
    # ### end Alembic commands ###
